version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: ts-api-gateway
    image: node:12
    working_dir: /usr/src/ts-api-gateway
    restart: always
    command: bash -c "npm install --only=prod && npm install -D nodemon && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ts-api-gateway
      - PORT=3000
      - JWT_SECRET=asdkj1@#dam21
      - ROOT_USER_NAME=root
      - ROOT_USER_EMAIL=root@mail.com
      - ROOT_USER_PASSWORD=123
    volumes:
      - ./dist/:/usr/src/ts-api-gateway/dist/
      - ./package.json:/usr/src/ts-api-gateway/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo
